version: '3.6'
services:
  mysql:
    image: ragedunicorn/mysql:1.0.1-stable
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - com.ragedunicorn.mysql.root_password
      - com.ragedunicorn.mysql.app_user
      - com.ragedunicorn.mysql.app_user_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.mysql.environment: "prod"
      com.ragedunicorn.mysql.description: "MySQL"
volumes:
  mysql_data: {}
secrets:
  com.ragedunicorn.mysql.root_password:
    external: true
  com.ragedunicorn.mysql.app_user:
    external: true
  com.ragedunicorn.mysql.app_user_password:
    external: true
