version: '3.4'
services:
  mysql:
    build: .
    image: ragedunicorn/mysql:1.0.0-dev
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    labels:
      com.ragedunicorn.mysql.environment: "dev"
      com.ragedunicorn.mysql.description: "MySQL"
volumes:
  mysql_data: {}
