version: '3.4'
services:
  mysql:
    build: .
    image: ragedunicorn/mysql:1.0.0-stable
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    labels:
      com.ragedunicorn.mysql.environment: "prod"
      com.ragedunicorn.mysql.description: "MySQL"
volumes:
  mysql_data: {}
