version: '3.7'
services:
  mysql:
    build: .
    image: ragedunicorn/mysql:${MYSQL_TAG_VERSION}-stable
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.mysql.environment: "prod"
      com.ragedunicorn.mysql.description: "MySQL"
volumes:
  mysql_data: {}
