version: '3.6'
services:
  mysql:
    build: .
    image: ragedunicorn/mysql:${MYSQL_TAG_VERSION}-stable
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.mysql.environment: "prod"
      com.ragedunicorn.mysql.description: "MySQL"
volumes:
  mysql_data: {}
